companies20_ticker = ["AAPL",
"AMZN",
"GOOGL",
"MSFT",
"TSLA",
"FB",
"BRK.B",
"JNJ",
"V",
"JPM",
"PG",
"WMT",
"KO",
"NFLX",
"PFE",
"DIS",
"NVDA",
"BABA",
"ADBE",
"MA"]

companies20_keywords = [
'organizations-Apple', 'AAPL',
'organizations-Amazon', 'Amazon.com', 'AMZN',
'organizations-Alphabet', 'organizations-google', 'google', 'GOOGL',
'organizations-Microsoft', 'Microsoft', 'MSFT',
'organizations-Tesla', 'Tesla', 'TSLA',
'organizations-Facebook', 'Facebook', 'organizations-Meta', 'Meta', 'FB',
'organizations-Berkshire', 'Berkshire', 'Berkshire Hathaway', 'BRK.B',
'organizations-Johnson & Johnson', 'organizations-Johnson and Johnson', 'Johnson and Johnson',  'JNJ',
'organizations-visa', 'Visa inc',
'organizations-JPMorgan', 'JPMorgan', 'Chase', 'JPM',
'organizations-Procter', 'Procter', 'PG',
'organizations-Walmart', 'Walmart', 'WMT',
'organizations-The Coca-Cola', 'organizations-Coca', 'Coca Cola', 'KO',
'organizations-Netflix', 'Netflix', 'NFLX',
'organizations-Pfizer', 'Pfizer', 'PFE',
'organizations-Walt', 'Walt Disney',
'organizations-Nvidia', 'Nvidia' 'NVDA',
'organizations-Alibaba', 'Alibaba',
'organizations-Adobe', 'Adobe Inc', 'ADBE',
'organizations-Mastercard', 'Mastercard']

companies20_keyword_dict = {
'apple': ['organizations-Apple', 'AAPL'],
'amazon': ['organizations-Amazon', 'Amazon.com', 'AMZN'],
'google': ['organizations-Alphabet', 'organizations-google', 'google', 'GOOGL'],
'microsoft': ['organizations-Microsoft', 'Microsoft', 'MSFT'],
'tesla': ['organizations-Tesla', 'Tesla', 'TSLA'],
'facebook': ['organizations-Facebook', 'Facebook', 'organizations-Meta', 'Meta', 'FB'],
'berkshire': ['organizations-Berkshire', 'Berkshire', 'Berkshire Hathaway', 'BRK.B'],
'johnson': ['organizations-Johnson & Johnson', 'organizations-Johnson and Johnson', 'Johnson and Johnson',  'JNJ'],
'visa': ['organizations-Visa', 'Visa inc'],
'jpmorgan': ['organizations-JPMorgan', 'JPMorgan', 'Chase', 'JPM'],
'procter': ['organizations-Procter', 'Procter', 'PG'],
'walmart': ['organizations-Walmart', 'Walmart', 'WMT'],
'coca': ['organizations-The Coca-Cola', 'organizations-Coca', 'Coca Cola', 'KO'],
'netflix': ['organizations-Netflix', 'Netflix', 'NFLX'],
'pfizer': ['organizations-Pfizer', 'Pfizer', 'PFE'],
'disney': ['organizations-Walt', 'Walt Disney'],
'nvidia': ['organizations-Nvidia', 'Nvidia' 'NVDA'],
'alibaba': ['organizations-Alibaba', 'Alibaba'],
'adobe': ['organizations-Adobe', 'Adobe Inc', 'ADBE'],
'mastercard': ['organizations-Mastercard', 'Mastercard']}

company100_name = ['Apple Inc.', 'Alibaba Group Holding Ltd.', 'Chevron Corporation', 'Exelon Corporation', 'McDonald Corporation', 'PepsiCo Inc.', 'Sherwin-Williams Company', 'Unilever PLC', 'AbbVie Inc.', 'Bank of America Corporation', 'Dominion Energy, Inc.', 'Meta Platforms, Inc.', '3M Company', 'Pfizer Inc.', 'Snap Inc.', 'UnitedHealth Group Incorporated', 'Abbott Laboratories', 'BHP Group Ltd.', 'DuPont de Nemours, Inc.', 'Freeport-McMoRan Inc.', 'Morgan Stanley', 'The Procter & Gamble Company', 'China Petroleum & Chemical Corporation', 'Union Pacific Corporation', 'Accenture plc', 'BHP Group Ltd.', 'Deere & Company', 'General Electric Company', 'Microsoft Corporation', 'Prologis, Inc.', 'The Southern Company', 'United Parcel Service, Inc.', 'Adobe Inc.', 'BP plc', 'Diageo plc', 'Alphabet Inc.', 'NextEra Energy, Inc.', 'Philip Morris International Inc.', 'Simon Property Group, Inc.', 'Visa Inc.', 'Automatic Data Processing, Inc.', 'Berkshire Hathaway Inc.', 'Danaher Corporation', 'The Home Depot, Inc.', 'Newmont Corporation', 'Public Storage', 'Sempra Energy', 'Vale S.A.', 'American Electric Power Company, Inc.', 'Citigroup Inc.', 'The Walt Disney Company', 'Honeywell International Inc.', 'Netflix, Inc.', 'PetroChina Company Limited', 'AT&T Inc.', 'Verizon Communications Inc.', 'American Tower Corporation', 'Caterpillar Inc.', 'Digital Realty Trust, Inc.', 'JD.com, Inc.', 'National Grid plc', 'PayPal Holdings, Inc.', 'Target Corporation', 'Welltower Inc.', 'Amazon.com, Inc.', 'Crown Castle International Corp.', 'Duke Energy Corporation', 'Johnson & Johnson', 'NIKE, Inc.', 'Royal Dutch Shell plc', 'Toyota Motor Corporation', 'Wells Fargo & Company', 'Air Products and Chemicals, Inc.', 'Charter Communications, Inc.', 'Ecolab Inc.', 'JPMorgan Chase & Co.', 'NVIDIA Corporation', 'Rio Tinto Group', 'Thermo Fisher Scientific Inc.', 'Walmart Inc.', 'ASML Holding N.V.', 'Comcast Corporation', 'The Estée Lauder Companies Inc.', 'The Coca-Cola Company', 'Novo Nordisk A/S', 'Raytheon Technologies Corporation', 'T-Mobile US, Inc.', 'Xcel Energy Inc.', 'Broadcom Inc.', 'ConocoPhillips', 'Enbridge Inc.', 'Eli Lilly and Company', 'Novartis AG', 'SBA Communications Corporation', 'Tesla, Inc.', 'Exxon Mobil Corporation', 'American Water Works Company, Inc.', 'Costco Wholesale Corporation', 'Equinix, Inc.', 'Lowe\'s Companies, Inc.', 'Realty Income Corporation', 'Starbucks Corporation', 'Taiwan Semiconductor Manufacturing Company Limited', 'The Boeing Company', 'Cisco Systems, Inc.', 'Equinor ASA', 'Mastercard Incorporated', 'Oracle Corporation', 'The Charles Schwab Corporation', 'TotalEnergies SE']
company100_name_shorten = ['Apple', 'Alibaba', 'Chevron', 'Exelon', 'McDonald', 'PepsiCo', 'Sherwin-Williams', 'Unilever', 'AbbVie', 'bank of America', 'Dominion', 'facebook', '3M', 'Pfizer', 'Snap', 'UnitedHealth', 'Abbott', 'BHP', 'DuPont', 'Freeport-McMoRan', 'Stanley', 'Procter', 'China Petroleum', 'Union Pacific', 'Accenture', 'BHP', 'Deere', 'General Electric', 'Microsoft', 'Prologis', 'Southern company', 'United Parcel', 'Adobe', 'BP plc', 'Diageo', 'Alphabet', 'NextEra', 'Philip Morris', 'Simon Property', 'Visa Inc', 'Automatic Data', 'Berkshire', 'Danaher', 'Home Depot', 'Newmont', 'Public Storage', 'Sempra Energy', 'Vale', 'American Electric', 'Citigroup', 'Disney', 'Honeywell', 'Netflix', 'PetroChina', 'AT&T', 'Verizon', 'American Tower', 'Caterpillar', 'Digital Realty Trust', 'JD.com', 'National Grid', 'PayPal', 'Target', 'Welltower', 'Amazon', 'Crown Castle', 'Duke Energy', 'Johnson & Johnson', 'NIKE', 'Royal Dutch', 'Toyota', 'Wells Fargo', 'Air Products and Chemicals', 'Charter Communications', 'Ecolab', 'JPMorgan', 'NVIDIA', 'Rio Tinto', 'Thermo Fisher', 'Walmart', 'ASML', 'Comcast', 'Estee', 'Coca', 'Novo', 'Raytheon', 'T-Mobile', 'Xcel', 'Broadcom', 'ConocoPhillips', 'Enbridge', 'Eli Lilly', 'Novartis', 'SBA', 'Tesla', 'Exxon', 'Water Works', 'Costco', 'Equinix', 'Lowe\'s Companies', 'Realty Income', 'Starbucks', 'Taiwan Semiconductor', 'The Boeing Company', 'Cisco', 'Equinor', 'Mastercard', 'Oracle', 'Charles Schwab', 'TotalEnergies']

company100_ticker = ['AAPL', 'BABA', 'CVX', 'EXC', 'MCD', 'PEP', 'SHW', 'UL', 'ABBV', 'BAC', 'D', 'FB', 'MMM', 'PFE', 'SNAP', 'UNH', 'ABT', 'BBL', 'DD', 'FCX', 'MS', 'PG', 'SNPMF', 'UNP', 'ACN', 'BHP', 'DE', 'GE', 'MSFT', 'PLD', 'SO', 'UPS', 'ADBE', 'BP', 'DEO', 'GOOG', 'NEE', 'PM', 'SPG', 'V', 'ADP', 'BRK-A', 'DHR', 'HD', 'NEM', 'PSA', 'SRE', 'VALE', 'AEP', 'C', 'DIS', 'HON', 'NFLX', 'PTR', 'T', 'VZ', 'AMT', 'CAT', 'DLR', 'JD', 'NGG', 'PYPL', 'TGT', 'WELL', 'AMZN', 'CCI', 'DUK', 'JNJ', 'NKE', 'RDS-B', 'TM', 'WFC', 'APD', 'CHTR', 'ECL', 'JPM', 'NVDA', 'RIO', 'TMO', 'WMT', 'ASML', 'CMCSA', 'EL', 'KO', 'NVO', 'RTX', 'TMUS', 'XEL', 'AVGO', 'COP', 'ENB', 'LLY', 'NVS', 'SBAC', 'TSLA', 'XOM', 'AWK', 'COST', 'EQIX', 'LOW', 'O', 'SBUX', 'TSM', 'BA', 'CSCO', 'EQNR', 'MA', 'ORCL', 'SCHW', 'TTE']

def getname(ticker):
    for i in company100_ticker:
        if ticker == i:
            return company100_name[i]
        
    return "Company X"

Company_desc100 = xcompanies = {
    "AAPL": "Apple Inc. is a multinational technology company that designs, manufactures, and sells consumer electronics, software, and services, including the iPhone, iPad, and Mac, operating in the technology industry.",
    "BABA": "Alibaba Group Holding Limited is a Chinese multinational conglomerate specializing in e-commerce, retail, internet, and technology, offering platforms for online sales, cloud computing, and digital payments.",
    "CVX": "Chevron Corporation is a global energy company engaged in the exploration, production, refining, and marketing of oil, natural gas, and petrochemical products, primarily operating in the energy sector.",
    "EXC": "Exelon Corporation is an American energy company that operates one of the largest utility networks, generating and distributing electricity and natural gas to consumers across the U.S.",
    "MCD": "McDonald's Corporation is the world’s largest fast-food restaurant chain, serving a wide range of burgers, fries, beverages, and other food items, operating in the quick-service restaurant industry.",
    "PEP": "PepsiCo, Inc. is a multinational food and beverage company that produces a wide range of products, including soft drinks, snacks, and packaged foods, with brands like Pepsi, Lay's, and Gatorade.",
    "SHW": "The Sherwin-Williams Company is an American paint and coatings manufacturer, supplying architectural, industrial, and automotive paints through its stores and distributors worldwide.",
    "UL": "Unilever PLC is a British multinational company that produces consumer goods, including food, beverages, cleaning agents, and personal care products, serving the global consumer goods industry.",
    "ABBV": "AbbVie Inc. is a global biopharmaceutical company that develops and markets pharmaceutical products for a range of therapeutic areas, including immunology, oncology, and neuroscience.",
    "BAC": "Bank of America Corporation is a multinational banking and financial services company offering a wide range of services including consumer banking, investment banking, and wealth management.",
    "D": "Dominion Energy, Inc. is an American utility company engaged in the generation, transmission, and distribution of electricity and natural gas, serving residential and commercial customers.",
    "FB": "Meta Platforms, Inc. (formerly Facebook) is a social media and technology company that operates platforms like Facebook, Instagram, and WhatsApp, specializing in digital advertising and virtual reality.",
    "MMM": "3M Company, also known as Minnesota Mining and Manufacturing, is a multinational conglomerate that produces a wide range of products including adhesives, abrasives, and personal protective equipment, serving industries such as healthcare, consumer goods, and industrial manufacturing.",
    "PFE": "Pfizer Inc. is a global biopharmaceutical company that develops, manufactures, and sells healthcare products, including vaccines, medicines, and treatments in the areas of oncology, immunology, and cardiology.",
    "SNAP": "Snap Inc. is an American technology company that develops and maintains Snapchat, a popular multimedia messaging app, and offers augmented reality and camera technology, focusing on the social media industry.",
    "UNH": "UnitedHealth Group Incorporated is a diversified healthcare company that provides healthcare coverage, benefits services, and information services, operating through its UnitedHealthcare and Optum divisions.",
    "ABT": "Abbott Laboratories is a global healthcare company that develops a wide range of medical devices, diagnostics, branded generic medicines, and nutritional products for various health conditions.",
    "BBL": "BHP Group Limited is a leading global resources company that is involved in the exploration, extraction, and processing of minerals such as iron ore, coal, and copper, primarily operating in the mining industry.",
    "DD": "DuPont de Nemours, Inc. is a global innovation leader in the chemical industry, specializing in the development of advanced materials, chemicals, and specialty products for various industries.",
    "FCX": "Freeport-McMoRan Inc. is a leading international mining company that primarily produces copper, gold, and molybdenum, serving industries such as energy, construction, and electronics.",
    "MS": "Morgan Stanley is a multinational investment bank and financial services company that provides wealth management, investment banking, trading, and advisory services to clients globally.",
    "PG": "The Procter & Gamble Company is a global consumer goods corporation that manufactures a wide range of products in categories such as beauty, grooming, health care, fabric care, and home care.",
    "SNPMF": "Sinopec Shanghai Petrochemical Company Limited is a Chinese petroleum and petrochemical company that produces a wide range of chemical products, serving industries like energy, materials, and manufacturing.",
    "UNP": "Union Pacific Corporation is a major American railroad company that operates freight transportation services across the Western United States, specializing in the shipment of goods like agricultural products, chemicals, and energy commodities.",
    "ACN": "Accenture plc is a global professional services company providing consulting, technology, and outsourcing services, helping businesses optimize operations and implement digital transformations.",
    "BHP": "BHP Group Limited is a global mining, metals, and petroleum company that explores, develops, and produces a range of natural resources, including iron ore, copper, coal, and petroleum products.",
    "DE": "Deere & Company is an American corporation that manufactures agricultural, construction, and forestry machinery, as well as diesel engines and other equipment, primarily serving the industrial and agriculture sectors.",
    "GE": "General Electric Company is a multinational conglomerate that operates in sectors like power, renewable energy, aviation, and healthcare, known for manufacturing industrial products and providing services in those areas.",
    "MSFT": "Microsoft Corporation is a leading technology company that develops, licenses, and sells software, hardware, and cloud computing services, best known for products like Windows, Office, and Azure.",
    "PLD": "Prologis, Inc. is a global real estate investment trust that specializes in owning, managing, and developing logistics facilities and industrial properties around the world.",
    "SO": "The Southern Company is a gas and electric utility holding company that provides energy services to millions of customers in the Southeastern United States, focusing on electricity generation, distribution, and transmission.",
    "UPS": "United Parcel Service, Inc. (UPS) is a global package delivery and supply chain management company, offering logistics, freight, and delivery services worldwide.",
    "ADBE": "Adobe Inc. is a multinational software company that provides creative, marketing, and document management solutions, best known for its products like Photoshop, Acrobat, and the Adobe Creative Cloud suite.",
    "BP": "BP plc (formerly British Petroleum) is a global energy company engaged in the production, refining, distribution, and marketing of oil, natural gas, and renewable energy solutions.",
    "DEO": "Diageo plc is a British multinational beverage company that produces and markets a wide range of alcoholic beverages, including spirits, beer, and wine, serving the global drinks industry with popular brands like Johnnie Walker, Guinness, and Smirnoff.",
    "GOOG": "Alphabet Inc., the parent company of Google, is a multinational technology conglomerate that provides a wide range of products and services, including online advertising technologies, search engine services, cloud computing, software, and hardware, operating primarily in the technology and internet services industry.",
    "NEE": "NextEra Energy, Inc. is a leading clean energy company that generates electricity from renewable sources such as wind and solar, and distributes electricity and natural gas to consumers across the U.S.",
    "PM": "Philip Morris International Inc. is a global tobacco company best known for manufacturing and selling cigarettes and smokeless tobacco products, including its flagship Marlboro brand.",
    "SPG": "Simon Property Group, Inc. is a leading real estate investment trust that owns, develops, and manages premier shopping, dining, entertainment, and mixed-use destinations worldwide.",
    "V": "Visa Inc. is a global financial services company that facilitates electronic funds transfers and payment solutions through its credit, debit, and prepaid card offerings for consumers and businesses.",
    "ADP": "Automatic Data Processing, Inc. (ADP) is a global provider of cloud-based human capital management solutions, including payroll, HR, and benefits administration for businesses of all sizes.",
    "BRK-A": "Berkshire Hathaway Inc. is a multinational conglomerate holding company led by Warren Buffett, owning subsidiaries engaged in diverse industries such as insurance, railroads, utilities, and manufacturing.",
    "DHR": "Danaher Corporation is a global science and technology innovator that designs, manufactures, and markets products and services in the fields of life sciences, diagnostics, and environmental industries.",
    "HD": "The Home Depot, Inc. is the largest home improvement retailer in the U.S., offering tools, construction products, appliances, and services for professional contractors and DIY customers.",
    "NEM": "Newmont Corporation is one of the world's largest gold mining companies, engaged in the production of gold and other precious metals, as well as the exploration and acquisition of mineral properties.",
    "PSA": "Public Storage is a real estate investment trust that operates self-storage facilities in the U.S. and Europe, providing secure storage units for personal, business, and vehicle storage needs.",
    "SRE": "Sempra Energy is a North American energy infrastructure company that develops, owns, and operates utility and energy infrastructure, with a focus on electricity generation and natural gas distribution.",
    "VALE": "Vale S.A. is a Brazilian multinational corporation engaged in the exploration and production of iron ore, nickel, and other minerals, operating primarily in the mining industry.",
    "AEP": "American Electric Power Company, Inc. is an American utility company that generates, transmits, and distributes electricity to millions of customers across the United States.",
    "C": "Citigroup Inc. is a global financial services company that provides a wide range of banking, investment, and financial services to consumers, corporations, and governments worldwide.",
    "DIS": "The Walt Disney Company is a global entertainment conglomerate that operates in industries such as media, theme parks, film production, and television networks, known for its iconic animated films and characters.",
    "HON": "Honeywell International Inc. is a multinational conglomerate that produces a variety of industrial products and services, including aerospace systems, building technologies, and performance materials.",
    "NFLX": "Netflix, Inc. is a global streaming entertainment service that provides on-demand TV shows, movies, and original programming to subscribers, operating primarily in the media and entertainment industry.",
    "PTR": "PetroChina Company Limited is a Chinese oil and gas company engaged in the exploration, production, refining, and marketing of petroleum products, primarily serving the energy sector.",
    "T": "AT&T Inc. is a telecommunications and media company that provides mobile and fixed-line communication services, digital entertainment, and high-speed internet to consumers and businesses.",
    "VZ": "Verizon Communications Inc. is a multinational telecommunications company that provides wireless and wireline communication services, internet access, and digital entertainment to customers worldwide.",
    "AMT": "American Tower Corporation is a real estate investment trust that owns, operates, and develops wireless and broadcast communication infrastructure, including cell towers and antenna systems.",
    "CAT": "Caterpillar Inc. is a global leader in the manufacturing of construction and mining equipment, diesel and natural gas engines, industrial turbines, and diesel-electric locomotives.",
    "DLR": "Digital Realty Trust, Inc. is a real estate investment trust that owns, acquires, and manages data centers, providing colocation, interconnection, and cloud computing services for technology companies.",
    "JD": "JD.com, Inc. is a Chinese e-commerce company that operates one of the largest online retail platforms in China, offering a wide range of products from electronics to apparel, with a focus on technology and logistics.",
    "NGG": "National Grid plc is a multinational electricity and gas utility company that operates energy transmission and distribution systems in the UK and northeastern U.S.",
    "PYPL": "PayPal Holdings, Inc. is a global technology company that provides an online payment platform, enabling digital and mobile payments for consumers and merchants around the world.",
    "TGT": "Target Corporation is an American retail company that operates a network of department stores offering a wide range of products, including apparel, electronics, and groceries.",
    "WELL": "Welltower Inc. is a real estate investment trust that focuses on owning, managing, and investing in senior living and healthcare facilities across the U.S., Canada, and the U.K.",
    "AMZN": "Amazon.com, Inc. is a multinational technology company that provides e-commerce, cloud computing, digital streaming, and artificial intelligence services, with its largest platform being the online retail marketplace.",
    "CCI": "Crown Castle International Corp. is a real estate investment trust that owns, operates, and leases wireless communication infrastructure, including cell towers and small cell networks across the U.S.",
    "DUK": "Duke Energy Corporation is one of the largest utility companies in the U.S., providing electricity and natural gas services to millions of customers across several states.",
    "JNJ": "Johnson & Johnson is a global healthcare company that develops medical devices, pharmaceuticals, and consumer health products, serving various healthcare needs worldwide.",
    "NKE": "Nike, Inc. is a multinational corporation that designs, manufactures, and sells athletic footwear, apparel, and accessories, operating in the sportswear and equipment industry.",
    "RDS-B": "Royal Dutch Shell plc (Shell) is a British-Dutch multinational oil and gas company involved in the exploration, production, refining, and distribution of oil and natural gas products.",
    "TM": "Toyota Motor Corporation is a global automotive manufacturer that produces a wide range of vehicles, including hybrid and electric cars, with a focus on innovation and sustainability.",
    "WFC": "Wells Fargo & Company is an American multinational financial services company offering a wide range of banking, investment, and mortgage products to consumers and businesses.",
    "APD": "Air Products and Chemicals, Inc. is a global industrial gases company that provides atmospheric and process gases, equipment, and services to industries such as energy, chemicals, and electronics.",
    "CHTR": "Charter Communications, Inc. is an American telecommunications and mass media company that provides cable television, internet, and phone services under the Spectrum brand.",
    "ECL": "Ecolab Inc. is a global provider of water, hygiene, and energy technologies and services, helping customers in food, healthcare, and industrial sectors maintain clean and safe environments.",
    "JPM": "JPMorgan Chase & Co. is a multinational investment bank and financial services company that provides a wide range of banking, investment, and asset management services globally.",
    "NVDA": "NVIDIA Corporation is a multinational technology company that designs and manufactures graphics processing units (GPUs), chipsets, and artificial intelligence solutions for gaming, data centers, and autonomous vehicles.",
    "RIO": "Rio Tinto Group is a multinational mining company that explores, develops, and produces a wide range of minerals, including iron ore, aluminum, and copper, operating in the metals and mining industry.",
    "TMO": "Thermo Fisher Scientific Inc. is a global biotechnology and life sciences company that provides scientific instruments, reagents, and laboratory services for research, healthcare, and industrial markets.",
    "WMT": "Walmart Inc. is a multinational retail corporation that operates hypermarkets, discount department stores, and grocery stores worldwide, offering a wide range of products at competitive prices.",
    "ASML": "ASML Holding N.V. is a Dutch semiconductor equipment manufacturer that designs and produces photolithography machines used to fabricate integrated circuits, serving the global semiconductor industry.",
    "CMCSA": "Comcast Corporation is an American telecommunications and media conglomerate that provides cable television, internet, and streaming services, as well as operating NBCUniversal’s media assets.",
    "EL": "The Estée Lauder Companies Inc. is a global leader in the beauty industry, manufacturing and marketing skincare, makeup, fragrance, and hair care products through its portfolio of brands.",
    "KO": "The Coca-Cola Company is a multinational beverage company that produces and sells a variety of non-alcoholic beverages, including its flagship Coca-Cola, along with juices, teas, and energy drinks.",
    "NVO": "Novo Nordisk A/S is a global healthcare company that develops and manufactures pharmaceutical products, specializing in diabetes care, obesity, and other chronic diseases.",
    "RTX": "Raytheon Technologies Corporation is a multinational aerospace and defense company that provides advanced systems and services for commercial, military, and government customers worldwide.",
    "TMUS": "T-Mobile US, Inc. is an American telecommunications company that provides wireless voice, messaging, and data services to millions of consumers and businesses across the U.S.",
    "XEL": "Xcel Energy Inc. is an American utility company that generates, transmits, and distributes electricity and natural gas, primarily operating in the Midwestern and Western U.S.",
    "AVGO": "Broadcom Inc. is a global technology company that designs, develops, and supplies a wide range of semiconductor and infrastructure software solutions for data centers, networking, and storage.",
    "COP": "ConocoPhillips is a multinational energy company engaged in the exploration, production, and transportation of oil and natural gas, with a focus on energy resources in North America and worldwide.",
    "ENB": "Enbridge Inc. is a Canadian multinational pipeline company that transports crude oil, natural gas, and liquids, and is also involved in renewable energy projects like wind and solar power.",
    "LLY": "Eli Lilly and Company is a global pharmaceutical company that develops and manufactures innovative medicines for a wide range of medical conditions, including diabetes, cancer, and mental health disorders.",
    "NVS": "Novartis International AG is a Swiss multinational pharmaceutical company that develops, manufactures, and markets healthcare products, focusing on innovative medicines in areas such as oncology, immunology, and ophthalmology.",
    "SBAC": "SBA Communications Corporation is a real estate investment trust that owns, operates, and leases wireless communication towers and infrastructure, providing wireless network connectivity across the U.S. and internationally.",
    "TSLA": "Tesla, Inc. is a leading electric vehicle and clean energy company that designs, manufactures, and sells electric cars, battery energy storage systems, and solar energy products.",
    "XOM": "ExxonMobil Corporation is a multinational oil and gas company engaged in the exploration, production, refining, and marketing of petroleum and natural gas products, as well as chemical manufacturing.",
    "AWK": "American Water Works Company, Inc. is the largest publicly traded water and wastewater utility company in the U.S., providing water services to millions of people in more than 40 states.",
    "COST": "Costco Wholesale Corporation is a multinational membership-based warehouse club that offers a wide range of products, including groceries, electronics, and household goods, at discounted prices.",
    "EQIX": "Equinix, Inc. is a global data center company that connects major businesses through its network of data centers, providing colocation, interconnection, and cloud solutions.",
    "LOW": "Lowe's Companies, Inc. is a home improvement retailer that offers a wide range of products, including appliances, tools, building materials, and home décor, serving consumers and professionals in the U.S. and Canada.",
    "O": "Realty Income Corporation is a real estate investment trust that owns and manages commercial properties, primarily leasing them to retail and industrial tenants on long-term net lease agreements.",
    "SBUX": "Starbucks Corporation is a global coffeehouse chain that sells premium coffee, tea, and other beverages, along with food items, operating in the retail, hospitality, and food and beverage industry.",
    "TSM": "Taiwan Semiconductor Manufacturing Company Limited (TSMC) is a multinational semiconductor manufacturing company that produces chips and integrated circuits for various industries, including consumer electronics, automotive, and telecommunications.",
    "BA": "The Boeing Company is an aerospace and defense company that designs, manufactures, and sells commercial airplanes, defense systems, and space technologies worldwide.",
    "CSCO": "Cisco Systems, Inc. is a multinational technology company that designs, manufactures, and sells networking hardware, telecommunications equipment, and other high-technology products and services.",
    "EQNR": "Equinor ASA is a Norwegian multinational energy company that engages in oil and gas exploration, production, refining, and renewable energy solutions, primarily operating in the energy sector.",
    "MA": "Mastercard Incorporated is a global technology company in the payments industry, providing financial services for consumers and businesses, including credit, debit, and prepaid card transactions.",
    "ORCL": "Oracle Corporation is a multinational technology company that offers software, hardware, and cloud services, specializing in database management systems and enterprise software solutions.",
    "SCHW": "The Charles Schwab Corporation is an American financial services company that provides a wide range of investment and banking services, including brokerage, wealth management, and retirement planning.",
    "TTE": "TotalEnergies SE is a French multinational energy company engaged in the exploration, production, and marketing of oil, gas, and renewable energy, with a focus on transitioning to cleaner energy sources."
}  
